### ISSUE TITLE
readme文件要补充一下啊兄弟

### ISSUE THREAD

**Issue by toyota-167** [KRISACHAN/ying-web#79]
readme文件要说一下用到哪些技术栈，还有如何启动项目。还有相关技术栈的版本。以及项目用到哪些技术亮点。

**Comment by KRISACHAN** [comment]
其实有。。。。。。。

**Comment by KRISACHAN** [comment]
每个子项目都有。。。

**Comment by KRISACHAN** [comment]
不过确实是应该补充到根目录里

**Comment by KRISACHAN** [comment]
补充完了 https://github.com/KRISACHAN/ying-web/blob/prod/README.md
@avida-1906

**Comment by KRISACHAN** [comment]
All the readme files have been completed. 
So, close this issue now ~
Thanks for the suggestion of @avida-1906
